# Generated by Django 4.0.2 on 2022-03-02 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computed_Molecular_Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inchikey', models.TextField()),
                ('molecular_formula', models.TextField()),
                ('calculated_molecular_weight', models.TextField(null=True)),
                ('pubchem_molecular_weight', models.TextField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
